version: "3"
services:
  backend:
    build:
      context: .
    ports:
      - "902:80"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
